version: "3.5"

services:

  jenkins:
    container_name: jenkins
    # nếu image: jenkins sẽ báo lỗi
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_vol:/var/jenkins_home

  sonarqube:
    container_name: sonarqube
    image: sonarqube
    ports:
      - "9000:9000"

volumes:
  jenkins_vol:
    # có trước nên là external, nếu chưa có thì docker-compose sẽ tự tạo --> bỏ dòng dưới
    external: true
